export const gunCollection = [
    `manufacturer`,
    `model`,
    `manufacturingDate`,
    `originCountry`,
    `caliber`,
    `serial`,
    `permit`,
    `acquisitionDate_unix`,
    `boughtFrom`,
    `mainColor`,
    `remarks`,
    `images`,
    `createdAt`,
    `lastModifiedAt`,
    `shotCount`,
    `tags`,
    `lastShotAt_unix`,
    `lastCleanedAt_unix`,
    `paidPrice`,
    `marketValue`,
    `cleanInterval`,
    `cleanInterval_CustomTime`,
    `cleanInterval_ShotCount`,
    `cleanIntervalDisplay`,
    `exFullAuto`,
    `highCapacityMagazine`,
    `short`,
    `fullAuto`,
    `launcher`,
    `decepticon`,
    `blooptoob`,
    `grandfather`,
    `customInventoryDesignation`
]

export const ammoCollection = [
    "id",
    "createdAt",
    "lastModifiedAt",
    "manufacturer",
    "designation",
    "originCountry",
    "caliber",
    "bulletType",
    "bulletWeight",
    "headstamp",
    "currentStock",
    "lastTopUpAt_unix",
    "criticalStock",
    "tags",
    "images",
    "customInventoryDesignation",
    "remarks",
]

export const silencerCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "caliber",
    "thread",
    "serial",
    "permit",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "lastCleanedAt_unix",
    "paidPrice",
    "marketValue",
    "cleanInterval",
    "cleanInterval_CustomTime",
    "cleanInterval_ShotCount",
    "cleanIntervalDisplay",
    "decibelRating",
    "material",
    "currentlyMountedOn",
    "customInventoryDesignation",
]

export const opticCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "serial",
    "reticle",
    "reticleColor",
    "footprint",
    "zoom",
    "unit",
    "clicksToUnitElevation",
    "clicksToUnitWindage",
    "material",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "lastCleanedAt_unix",
    "paidPrice",
    "marketValue",
    "cleanInterval",
    "cleanInterval_CustomTime",
    "cleanInterval_ShotCount",
    "cleanIntervalDisplay",
    "currentlyMountedOn",
    "batteryLastChangedAt_unix",
    "customInventoryDesignation",
]

export const scopeCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "serial",
    "reticle",
    "reticleColor",
    "zoom",
    "unit",
    "clicksToUnitElevation",
    "clicksToUnitWindage",
    "material",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "lastCleanedAt_unix",
    "paidPrice",
    "marketValue",
    "cleanInterval",
    "cleanInterval_CustomTime",
    "cleanInterval_ShotCount",
    "cleanIntervalDisplay",
    "currentlyMountedOn",
    "batteryLastChangedAt_unix",
    "customInventoryDesignation",
]

export const lightLaserCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "serial",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "permit",
    "lumen",
    "candela",
    "wavelength",
    "laserPower",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "paidPrice",
    "marketValue",
    "currentlyMountedOn",
    "batteryLastChangedAt_unix",
    "customInventoryDesignation",
]

export const conversionCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "caliber",
    "serial",
    "permit",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "lastCleanedAt_unix",
    "paidPrice",
    "marketValue",
    "cleanInterval",
    "cleanInterval_CustomTime",
    "cleanInterval_ShotCount",
    "cleanIntervalDisplay",
    "currentlyMountedOn",
    "customInventoryDesignation",
]

export const barrelCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "caliber",
    "thread",
    "barrelLength",
    "serial",
    "permit",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "lastCleanedAt_unix",
    "paidPrice",
    "marketValue",
    "cleanInterval",
    "cleanInterval_CustomTime",
    "cleanInterval_ShotCount",
    "cleanIntervalDisplay",
    "currentlyMountedOn",
    "customInventoryDesignation",
]

export const magazineCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "caliber",
    "capacity",
    "currentStock",
    "platform",
    "serial",
    "permit",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "shotCount",
    "tags",
    "lastShotAt_unix",
    "lastCleanedAt_unix",
    "paidPrice",
    "marketValue",
    "cleanInterval",
    "cleanInterval_CustomTime",
    "cleanInterval_ShotCount",
    "cleanIntervalDisplay",
    "material",
    "currentlyMountedOn",
    "customInventoryDesignation",
]

export const miscAccessoryCollection = [
    "id",
    "manufacturer",
    "model",
    "manufacturingDate",
    "originCountry",
    "serial",
    "acquisitionDate_unix",
    "boughtFrom",
    "mainColor",
    "remarks",
    "images",
    "createdAt",
    "lastModifiedAt",
    "tags",
    "paidPrice",
    "marketValue",
    "currentlyMountedOn",
    "customInventoryDesignation",
]

export const bookCollection = [
    "id",
    "createdAt",
    "lastModifiedAt",
    "images",
    "tags",
    "title",
    "volume",
    "subtitle",
    "series",
    "author",
    "publisher",
    "isbn",
    "publishingDate",
    "language",
    "edition",
    "pages",
    "format",
    "acquisitionDate_unix",
    "paidPrice",
    "boughtFrom",
    "marketValue",
    "remarks",
    "customInventoryDesignation",
]

export const printMagazineCollection = [
    
]

export const swissMilitaryRegulationCollection = [
    
]

export const literatureMiscCollection = [
    
]

export const dieCollection = [
    "id",
    "createdAt",
    "lastModifiedAt",
    "images",
    "tags",
    "manufacturer",
    "model",
    "caliber",
    "dieSeries",
    "group",
    "partNumber",
    "shellHolder",
    "acquisitionDate_unix",
    "paidPrice",
    "boughtFrom",
    "marketValue",
    "remarks",
    "customInventoryDesignation",
    "qrCode",
]

export const bulletCollection = [
    
]

export const caseCollection = [
    
]

export const primerCollection = [
    
]

export const powderCollection = [
    
]

export const reloadingMiscCollection = [
    
]